name: Daily Report Generator

on:
  schedule:
    - cron: '* * * * *'  # Every day at 9 AM UTC
  workflow_dispatch:       # Allow manual run

jobs:
  generate-report:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: "production"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run report script
        run: ./report.sh

      - name: Upload report.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: report.txt

      - name: Notify via Slack
        if: ${{ success() }}
        run: echo "Slack notification would go here..."
